<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>calculator.ico</ApplicationIcon>
    <AssemblyName>CalculadoraDeImposto</AssemblyName>
    <AssemblyTitle>Calculadora de Imposto</AssemblyTitle>
    <Product>Calculadora de Imposto</Product>
    <Description>Calculadora de imposto de renda, INSS e FGTS.</Description>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="calculator.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="BancoDados\calculoIrrf.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
