CREATE TABLE IRRF(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Competencia DATE NOT NULL,
	Faixa INTEGER NOT NULL,
	Valor DECIMAL(15,2) NOT NULL,
	Porcentagem DECIMAL(15,2) NOT NULL,
	Deducao DECIMAL(15,2) NOT NULL
);
CREATE TABLE INSS(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Competencia DATE NOT NULL,
	Faixa DECIMAL(15,2) NOT NULL,
	Valor DECIMAL(15,2) NOT NULL,
	Porcentagem DECIMAL(15,2) NOT NULL
);
CREATE TABLE Simplificado(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Competencia DATE NOT NULL,
	Valor DECIMAL(15,2) NOT NULL
);
CREATE TABLE Dependente(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Competencia DATE NOT NULL,
	Valor DECIMAL(15,2) NOT NULL
);
CREATE TABLE DescontoMinimo(
	Id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Competencia DATE NOT NULL,
	Valor DECIMAL(15,2) NOT NULL
);