// <auto-generated />
using System;
using CalculoIRRF.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoIRRF.Migrations
{
    [DbContext(typeof(CalculoImpostoContext))]
    [Migration("20250303123820_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CalculoIRRF.Model.Dependente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dependente");
                });

            modelBuilder.Entity("CalculoIRRF.Model.DescontoMinimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimo");
                });

            modelBuilder.Entity("CalculoIRRF.Model.Inss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Teto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inss");
                });

            modelBuilder.Entity("CalculoIRRF.Model.InssGov", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseCaculo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InssGov");
                });

            modelBuilder.Entity("CalculoIRRF.Model.Irrf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deducao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Porcentagem")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Irrf");
                });

            modelBuilder.Entity("CalculoIRRF.Model.IrrfRfb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Aliquota")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseCaculo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deducao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dependente")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Simplificado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IrrfRfb");
                });

            modelBuilder.Entity("CalculoIRRF.Model.Simplificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simplificado");
                });
#pragma warning restore 612, 618
        }
    }
}
