// <auto-generated />
using System;
using CalculoIRRF.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoIRRF.Migrations
{
    [DbContext(typeof(CalculoImpostoContext))]
    [Migration("20251028005101_V4")]
    partial class V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("CalculoIRRF.Model.Dependente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Dependente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 189.59
                        });
                });

            modelBuilder.Entity("CalculoIRRF.Model.DescontoMinimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DescontoMinimo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 10.0
                        });
                });

            modelBuilder.Entity("CalculoIRRF.Model.Inss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Porcentagem")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Inss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competencia = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1045.0
                        },
                        new
                        {
                            Id = 2,
                            Competencia = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2089.5999999999999
                        },
                        new
                        {
                            Id = 3,
                            Competencia = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 3134.4000000000001
                        },
                        new
                        {
                            Id = 4,
                            Competencia = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 6101.0600000000004
                        },
                        new
                        {
                            Id = 5,
                            Competencia = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1212.0
                        },
                        new
                        {
                            Id = 6,
                            Competencia = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2452.6700000000001
                        },
                        new
                        {
                            Id = 7,
                            Competencia = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 3679.0
                        },
                        new
                        {
                            Id = 8,
                            Competencia = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 7087.2200000000003
                        },
                        new
                        {
                            Id = 9,
                            Competencia = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1302.0
                        },
                        new
                        {
                            Id = 10,
                            Competencia = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2571.29
                        },
                        new
                        {
                            Id = 11,
                            Competencia = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 3856.9400000000001
                        },
                        new
                        {
                            Id = 12,
                            Competencia = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 7507.4899999999998
                        },
                        new
                        {
                            Id = 13,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1320.0
                        },
                        new
                        {
                            Id = 14,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2571.29
                        },
                        new
                        {
                            Id = 15,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 3856.9400000000001
                        },
                        new
                        {
                            Id = 16,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 7507.4899999999998
                        },
                        new
                        {
                            Id = 17,
                            Competencia = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1412.0
                        },
                        new
                        {
                            Id = 18,
                            Competencia = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2666.6799999999998
                        },
                        new
                        {
                            Id = 19,
                            Competencia = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 4000.0300000000002
                        },
                        new
                        {
                            Id = 20,
                            Competencia = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 7786.0200000000004
                        },
                        new
                        {
                            Id = 21,
                            Competencia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 1,
                            Porcentagem = 7.5,
                            Valor = 1518.0
                        },
                        new
                        {
                            Id = 22,
                            Competencia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 2,
                            Porcentagem = 9.0,
                            Valor = 2793.8800000000001
                        },
                        new
                        {
                            Id = 23,
                            Competencia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 3,
                            Porcentagem = 12.0,
                            Valor = 4190.8299999999999
                        },
                        new
                        {
                            Id = 24,
                            Competencia = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Faixa = 4,
                            Porcentagem = 14.0,
                            Valor = 8157.4099999999999
                        });
                });

            modelBuilder.Entity("CalculoIRRF.Model.InssGov", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Aliquota")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseCaculo")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Vigencia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InssGov");
                });

            modelBuilder.Entity("CalculoIRRF.Model.Irrf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("Deducao")
                        .HasColumnType("REAL");

                    b.Property<int>("Faixa")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Porcentagem")
                        .HasColumnType("REAL");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Irrf");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 0.0,
                            Faixa = 1,
                            Porcentagem = 0.0,
                            Valor = 1903.98
                        },
                        new
                        {
                            Id = 2,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 142.80000000000001,
                            Faixa = 2,
                            Porcentagem = 7.5,
                            Valor = 2826.6500000000001
                        },
                        new
                        {
                            Id = 3,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 354.80000000000001,
                            Faixa = 3,
                            Porcentagem = 15.0,
                            Valor = 3751.0500000000002
                        },
                        new
                        {
                            Id = 4,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 636.13,
                            Faixa = 4,
                            Porcentagem = 22.5,
                            Valor = 4664.6800000000003
                        },
                        new
                        {
                            Id = 5,
                            Competencia = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 869.36000000000001,
                            Faixa = 5,
                            Porcentagem = 27.5,
                            Valor = 99999999999.990005
                        },
                        new
                        {
                            Id = 6,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 0.0,
                            Faixa = 1,
                            Porcentagem = 0.0,
                            Valor = 2112.0
                        },
                        new
                        {
                            Id = 8,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 158.40000000000001,
                            Faixa = 2,
                            Porcentagem = 7.5,
                            Valor = 2826.6500000000001
                        },
                        new
                        {
                            Id = 9,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 370.39999999999998,
                            Faixa = 3,
                            Porcentagem = 15.0,
                            Valor = 3751.0500000000002
                        },
                        new
                        {
                            Id = 10,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 651.73000000000002,
                            Faixa = 4,
                            Porcentagem = 22.5,
                            Valor = 4664.6800000000003
                        },
                        new
                        {
                            Id = 11,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 884.96000000000004,
                            Faixa = 5,
                            Porcentagem = 27.5,
                            Valor = 99999999999.990005
                        },
                        new
                        {
                            Id = 12,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 0.0,
                            Faixa = 1,
                            Porcentagem = 0.0,
                            Valor = 2259.1999999999998
                        },
                        new
                        {
                            Id = 13,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 169.44,
                            Faixa = 2,
                            Porcentagem = 7.5,
                            Valor = 2826.6500000000001
                        },
                        new
                        {
                            Id = 14,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 381.44,
                            Faixa = 3,
                            Porcentagem = 15.0,
                            Valor = 3751.0500000000002
                        },
                        new
                        {
                            Id = 15,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 662.76999999999998,
                            Faixa = 4,
                            Porcentagem = 22.5,
                            Valor = 4664.6800000000003
                        },
                        new
                        {
                            Id = 16,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 896.0,
                            Faixa = 5,
                            Porcentagem = 27.5,
                            Valor = 99999999999.990005
                        },
                        new
                        {
                            Id = 17,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 0.0,
                            Faixa = 1,
                            Porcentagem = 0.0,
                            Valor = 2428.8000000000002
                        },
                        new
                        {
                            Id = 18,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 169.44,
                            Faixa = 2,
                            Porcentagem = 7.5,
                            Valor = 2826.6500000000001
                        },
                        new
                        {
                            Id = 19,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 381.44,
                            Faixa = 3,
                            Porcentagem = 15.0,
                            Valor = 3751.0500000000002
                        },
                        new
                        {
                            Id = 20,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 662.76999999999998,
                            Faixa = 4,
                            Porcentagem = 22.5,
                            Valor = 4664.6800000000003
                        },
                        new
                        {
                            Id = 21,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deducao = 896.0,
                            Faixa = 5,
                            Porcentagem = 27.5,
                            Valor = 99999999999.990005
                        });
                });

            modelBuilder.Entity("CalculoIRRF.Model.IrrfRfb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Aliquota")
                        .HasColumnType("REAL");

                    b.Property<double>("BaseCaculo")
                        .HasColumnType("REAL");

                    b.Property<double>("Deducao")
                        .HasColumnType("REAL");

                    b.Property<double>("Dependente")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequencia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Simplificado")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Vigencia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IrrfRfb");
                });

            modelBuilder.Entity("CalculoIRRF.Model.Simplificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Simplificado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Competencia = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 528.0
                        },
                        new
                        {
                            Id = 2,
                            Competencia = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 564.79999999999995
                        },
                        new
                        {
                            Id = 3,
                            Competencia = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Valor = 607.20000000000005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
